---

  - name: "Copy files"
    become: true
    copy:
      src: /root/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz
    shell : |
        cd /home/ubuntu/
        tar xvzf artifact.tar.gz -C .
  - name: "Start app"
    become: true
    shell : |
        cd /home/ubuntu/
        npm install
        pm2 stop default
        pm2 start npm -- start


